// Convert any binary file (e.g. a .vgm) into a C byte-array header for MSXgl.
// Usage: node tools/bin2c.mjs <input> <output.h> <arrayName>
import { readFileSync, writeFileSync } from "node:fs";

const input = process.argv[2];
const out = process.argv[3] || "data.h";
const name = process.argv[4] || "g_Data";
if (!input) {
  console.error("Usage: node tools/bin2c.mjs <input> <output.h> <arrayName>");
  process.exit(1);
}

const bytes = readFileSync(input);
let body = "";
for (let i = 0; i < bytes.length; i++) {
  if (i % 16 === 0) body += "\n\t";
  body += "0x" + bytes[i].toString(16).padStart(2, "0") + ", ";
}

const header = `// Auto-generated by tools/bin2c.mjs from "${input}" — do not edit by hand.
// ${bytes.length} bytes.

const unsigned char ${name}[] = {${body}
};
`;

writeFileSync(out, header);
console.log(`Wrote ${out}: ${name}[${bytes.length}]`);
