// Generate a VGM from MML and emit it as a C byte array header for MSXgl.
// Usage: node tools/vgm2c.mjs <out.h> <arrayName>
import { buildVGM } from "../public/vgm.js";
import { writeFileSync } from "node:fs";

const out = process.argv[2] || "mytest_vgm.h";
const name = process.argv[3] || "g_MyVGM";

// A deliberately recognizable C-major piece so playback is unmistakably "ours":
// arpeggio melody, chord-tone harmony, simple bass. 120 BPM, loops at 4s.
const channels = {
  A: "o4 [c8 e8 g8 >c8 <b8 g8 e8 c8]2",
  B: "o3 [c4 e4 g4 e4]2",
  C: "o2 [c4 c4 g4 g4]2",
};
const bpm = 120;

const bytes = buildVGM(channels, bpm, true);

// Format as a C array, 16 bytes per line.
let body = "";
for (let i = 0; i < bytes.length; i++) {
  if (i % 16 === 0) body += "\n\t";
  body += "0x" + bytes[i].toString(16).padStart(2, "0") + ", ";
}

const header = `// Auto-generated by tools/vgm2c.mjs — do not edit by hand.
// Source MML: A="${channels.A}" B="${channels.B}" C="${channels.C}" @ ${bpm} BPM
// Standard PSG (AY-3-8910) VGM 1.51, ${bytes.length} bytes.

const unsigned char ${name}[] = {${body}
};
`;

writeFileSync(out, header);
console.log(`Wrote ${out}: ${name}[${bytes.length}]`);
